<?php
// 3.0.7 MariaDB
$langues = array(
	'langue' => 'Română',
	'locale' => 'romanian',
	'titreHtml' => 'Index-ul WAMPSERVER',
	'titreConf' => 'Configurare Server',
	'versa' => 'Versiune Apache:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/en/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/en/',
	'versp' => 'Versiune PHP:',
	'server' => 'Aplicaţie Server:',
	'documentation' => 'Documentaþie',
	'docp' => 'www.php.net/manual/en/',
	'versm' => 'Versiune MySQL:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'Versiune MariaDB: ',
	'docmaria' => 'mariadb.com/kb/en/mariadb/documentation',
	'phpExt' => 'Extensii încarcate: ',
	'titrePage' => 'Instrumente',
	'txtProjet' => 'Proiectele Tale',
	'txtNoProjet' => 'Nu există niciun Proiect.<br />Pentru a crea unul, nu trebuie decât sa creaţi un director (folder) în \'www\'.',
	'txtAlias' => 'Aliasuri',
	'txtNoAlias' => 'Nu există niciun Alias.<br />Pentru a crea unul, foloseşte meniul WAMPSERVER.',
	'txtVhost' => 'VirtualHost',
	'txtServerName' => 'Numele Serverului %s are o eroare de sintaxă în fişierul %s',
	'txtServerNameIp' => 'IP %s pentru Numele Serverului %s este invalid în fişierul %s',
	'txtVhostNotClean' => 'Fişierul %s nu a fost golit. Rămân exemple de VirtualHost precum: dummy-host.example.com',
	'txtNoVhost' => 'Niciun VirtualHost definit. Adaugă câte unul pentru fiecare proiect ăn fişierul: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Şterge comentariul sau adaugă linia <i>Include conf/extra/httpd-vhosts.conf</i> în fişierul wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Fişierul: %s nu există',
	'txtNoPath' => 'Calea %s pentru %s nu există (Fişierul %s)',
	'txtNotWritable' => 'Fişierul: %s nu este modificabil',
	'txtNbNotEqual' => 'Numărul de %s nu se potriveşte cu numărul de %s în fişierul %s',
	'txtAddVhost' => 'Adaugă un Virtual Host',
	'txtPortNumber' => 'Numărul Portului pentru %s este incorect sau diferă de cel din fişierul %s',
	'txtCorrected' => 'Unele erori VirtualHosts pot fi corectate.',
	'forum' => 'Forumul Wampserver',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Portul definit pentru Apache: ',
	'mysqlportUsed' => 'Portul definit pentru MySQL: ',
	'mariaportUsed' => 'Portul definit pentru MariaDB: ',
	'nolocalhost' => 'Nu este o idee bună sa adăugaţi localhost în adresa (url-ul) proiectelor. Este recomandată definirea unui VirtualHost corespunzător în fişierul<br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br />şi evitarea folosirii localhost în adrese (url).',
	);
?>